---
title: "sta130proj"
output: html_document
date: "2023-03-18"
---
ctil + Alt + I to insert codechunk(window)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r cars}
library(tidyverse)
```

```{r}
# load basic data
library(rhdf5)
header <- h5ls("STA130_APOGEE.h5")
header
```

```{r}
glimpse(header)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


```{r}
# test a simple visualization from two tibble we are focusing on
effective_temp <- "STA130_APOGEE.h5" %>% h5read("teff") %>% as_tibble()
logg_gravity <- "STA130_APOGEE.h5" %>% h5read("logg") %>% as_tibble()
ggplot() + aes(x=effective_temp$value, y=logg_gravity$value) + geom_bin_2d(bins=200)
```

```{r}
# this is the linear regression analyze of our second research problem
et = "STA130_APOGEE.h5" %>% h5read("logg")
loggra = "STA130_APOGEE.h5" %>% h5read("teff")
df <- data.frame(et, loggra)
model <- lm(loggra ~ et, data = df) %>% summary
ggplot(df, aes(x = et, y = loggra)) +
  geom_point() +
  geom_smooth(method = "lm")
df
model
```

